import './global.css'
import { Toaster } from 'react-hot-toast'

export const metadata = {
  title: 'Tally App',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="min-h-full flex flex-col bg-slate-50 text-slate-900">
        {children}
        <Toaster position="bottom-center" />
      </body>
    </html>
  )
}
